CREATE OR REPLACE DATABASE CURRENCY_DB;
CREATE OR REPLACE SCHEMA CURRENCY_DB.raw;

CREATE OR REPLACE FILE FORMAT CURRENCY_DB.raw.json_file_format
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = TRUE
  IGNORE_UTF8_ERRORS = TRUE;

CREATE OR REPLACE STAGE CURRENCY_DB.raw.bucket_exchange_rates
  URL = 's3://bucket-exchange-rates/'
  CREDENTIALS = (
    AWS_KEY_ID = 'COLE_SEU_AWS_ACCESS_KEY_ID_AQUI'
    AWS_SECRET_KEY = 'COLE_SEU_AWS_SECRET_ACCESS_KEY_AQUI'
  )
  FILE_FORMAT = CURRENCY_DB.raw.json_file_format;

CREATE OR REPLACE TABLE CURRENCY_DB.raw.raw_exchange_rates (
  raw_data VARIANT,
  inserted_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);